language: php

dist: jammy
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files
        - .phpunit

env:
    global:
        - SYMFONY_PHPUNIT_DIR=.phpunit

matrix:
    fast_finish: true
    include:
        - php: 7.4
          env: SYMFONY_VERSION=5.4.x
        - php: 8.0
          env: SYMFONY_VERSION=5.4.x
        - php: 8.1
          env: SYMFONY_VERSION=5.4.x
        - php: 8.2
          env: SYMFONY_VERSION=5.4.x
        - php: 8.0
          env: SYMFONY_VERSION=6.2.x
        - php: 8.1
          env: SYMFONY_VERSION=6.2.x
        - php: 8.2
          env: SYMFONY_VERSION=6.2.x
        # Test against dev versions
        - php: nightly
          env: DEPENDENCIES=dev SYMFONY_VERSION=6.2.x

    allow_failures:
        - env: DEPENDENCIES=dev

before_install:
    - composer self-update
    - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:"$SYMFONY_VERSION"; fi

install:
    - composer update $COMPOSER_FLAGS
    - ./vendor/bin/simple-phpunit install

script: ./vendor/bin/simple-phpunit -v --coverage-text
